name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Download dependencies
        run: go mod download

      - name: Generate mocks
        run: make mocks

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Build
        run: make build
